### ISSUE TITLE
Krita 5.1.1. Error message UnboundLocalError: local variable 'elementType' referenced before assignment

### ISSUE THREAD

**Issue by cesar-pix** [KnowZero/Krita-LazyTextTool-Prototype#1]
Hello, first off, I would like to thanks you a lot for the impressive effort of pulling out such an awesome and so needed plugin, it should be the default text editor, just like that, this is a major UX and UI improvement. I didn't really went for the programming side of things, but would really like to help this plugin improvement, I would even try to fix this bug if I knew any python, but I'm in POP!OS using Krita 5.1.1 and every now and then I get this error message:

```
UnboundLocalError
Python 3.9.9: /usr/bin/python3
Tue Sep 27 19:41:58 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py in eventFilter(self=<LazyTextTool.LazyTextTool.LazyTextTool.toolboxButtonFilter object>, obj=<PyQt5.QtWidgets.QToolButton object>, event=<PyQt5.QtGui.QPaintEvent object>)
   30                     if obj.isChecked():
   31                         print ("OPEN CANVAS FROM FILTER")
   32                         LazyTextTool.openTextCanvas(self.textTool)
   33                     else:
   34                         if self.textTool.currentTextCanvas is not None:
global LazyTextTool = <class 'LazyTextTool.LazyTextTool.LazyTextTool'>
LazyTextTool.openTextCanvas = <function LazyTextTool.openTextCanvas>
self = <LazyTextTool.LazyTextTool.LazyTextTool.toolboxButtonFilter object>
self.textTool = <LazyTextTool.LazyTextTool.LazyTextTool object>

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py in openTextCanvas(self=<LazyTextTool.LazyTextTool.LazyTextTool object>)
  655             if self.currentLayer.type() == 'vectorlayer':
  656                 shapes = self.currentLayer.shapes()
  657                 self.currentTextCanvas.fillLayer(self.currentLayer, shapes)
  658 
  659             self.currentTextCanvas.view.setFocus()
self = <LazyTextTool.LazyTextTool.LazyTextTool object>
self.currentTextCanvas = <LazyTextTool.LazyTextTool.LazyTextTool.TextCanvas object>
self.currentTextCanvas.fillLayer = <bound method LazyTextTool.TextCanvas.fillLayer ...ool.LazyTextTool.LazyTextTool.TextCanvas object>>
self.currentLayer = <PyKrita.krita.VectorLayer object>
shapes = [<PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>]

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py in fillLayer(self=<LazyTextTool.LazyTextTool.LazyTextTool.TextCanvas object>, layer=<PyKrita.krita.VectorLayer object>, shapes=[<PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>, <PyKrita.krita.Shape object>])
   75         def fillLayer(self, layer, shapes):
   76             for shape in shapes:
   77                 self.textObjectFromLayerAndShape([ layer, shape ])
   78 
   79         def textObjectFromLayerAndShape(self, textItem):
self = <LazyTextTool.LazyTextTool.LazyTextTool.TextCanvas object>
self.textObjectFromLayerAndShape = <bound method LazyTextTool.TextCanvas.textObject...ool.LazyTextTool.LazyTextTool.TextCanvas object>>
layer = <PyKrita.krita.VectorLayer object>
shape = <PyKrita.krita.Shape object>

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py in textObjectFromLayerAndShape(self=<LazyTextTool.LazyTextTool.LazyTextTool.TextCanvas object>, textItem=[<PyKrita.krita.VectorLayer object>, <PyKrita.krita.Shape object>])
  115 
  116 
  117             docContent = LazyTextUtils.svgToDocument(svgContent)
  118 
  119             if docContent[1]['version'] == 0 and textItem[1].name() is not None:
docContent undefined
global LazyTextUtils = <class 'LazyTextTool.LazyTextToolFunc.LazyTextUtils'>
LazyTextUtils.svgToDocument = <function LazyTextUtils.svgToDocument>
svgContent = '<rect id="shape0" transform="matrix(1.1065020916...-linejoin="bevel" width="388.5" height="218.25"/>'

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextToolFunc.py in svgToDocument(svgContent='<rect id="shape0" transform="matrix(1.1065020916...-linejoin="bevel" width="388.5" height="218.25"/>')
  680     @staticmethod
  681     def svgToDocument(svgContent):
  682         htmlData = LazyTextUtils.svgToHtml2(svgContent)
  683         htmlData['content'] = re.sub(r'(<p[^>]*?>)[ ]*?</p>',r'\1&nbsp;</p>', htmlData['content'])
  684         print ("HTML2", htmlData['content'])
htmlData undefined
global LazyTextUtils = <class 'LazyTextTool.LazyTextToolFunc.LazyTextUtils'>
LazyTextUtils.svgToHtml2 = <function LazyTextUtils.svgToHtml2>
svgContent = '<rect id="shape0" transform="matrix(1.1065020916...-linejoin="bevel" width="388.5" height="218.25"/>'

 /home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextToolFunc.py in svgToHtml2(svgContent='<rect id="shape0" transform="matrix(1.1065020916...-linejoin="bevel" width="388.5" height="218.25"/>')
  790 
  791                 print ("ELM", elementList[i]['el'].attrib )
  792                 if elementType in tagConvert:
  793                     if elementType == "block":
  794                         blockSettings.append({ 'lines':[{}], 'fragments':[], 'attrib':{}, 'lineheight':0 })
elementType undefined
tagConvert = {'block': {'tag': 'p'}, 'line': {'tag': 'span'}, 'mark': {'tag': 'span'}, 'root': {'tag': 'body'}}
UnboundLocalError: local variable 'elementType' referenced before assignment
    __cause__ = None
    __class__ = <class 'UnboundLocalError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of UnboundLocalError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of UnboundLocalError object>
    __doc__ = 'Local name referenced but not bound to a value.'
    __eq__ = <method-wrapper '__eq__' of UnboundLocalError object>
    __format__ = <built-in method __format__ of UnboundLocalError object>
    __ge__ = <method-wrapper '__ge__' of UnboundLocalError object>
    __getattribute__ = <method-wrapper '__getattribute__' of UnboundLocalError object>
    __gt__ = <method-wrapper '__gt__' of UnboundLocalError object>
    __hash__ = <method-wrapper '__hash__' of UnboundLocalError object>
    __init__ = <method-wrapper '__init__' of UnboundLocalError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of UnboundLocalError object>
    __lt__ = <method-wrapper '__lt__' of UnboundLocalError object>
    __ne__ = <method-wrapper '__ne__' of UnboundLocalError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of UnboundLocalError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of UnboundLocalError object>
    __repr__ = <method-wrapper '__repr__' of UnboundLocalError object>
    __setattr__ = <method-wrapper '__setattr__' of UnboundLocalError object>
    __setstate__ = <built-in method __setstate__ of UnboundLocalError object>
    __sizeof__ = <built-in method __sizeof__ of UnboundLocalError object>
    __str__ = <method-wrapper '__str__' of UnboundLocalError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("local variable 'elementType' referenced before assignment",)
    with_traceback = <built-in method with_traceback of UnboundLocalError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py", line 32, in eventFilter
    LazyTextTool.openTextCanvas(self.textTool)
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py", line 657, in openTextCanvas
    self.currentTextCanvas.fillLayer(self.currentLayer, shapes)
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py", line 77, in fillLayer
    self.textObjectFromLayerAndShape([ layer, shape ])
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextTool.py", line 117, in textObjectFromLayerAndShape
    docContent = LazyTextUtils.svgToDocument(svgContent)
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextToolFunc.py", line 682, in svgToDocument
    htmlData = LazyTextUtils.svgToHtml2(svgContent)
  File "/home/cesar/.var/app/org.kde.krita/data/krita/pykrita/LazyTextTool/LazyTextToolFunc.py", line 792, in svgToHtml2
    if elementType in tagConvert:
UnboundLocalError: local variable 'elementType' referenced before assignment

```
Hope it helps in someway at least reporting the bug, and hope I can make something about it, because this tool is amazing

**Comment by KnowZero** [comment]
This happens when you click on an element right? Does it happen randomly or on some text?

Pick the vector layer in question and go to Tools->Scripter

and run this:

```print ( Krita.instance().activeDocument().activeNode().toSvg() )```

Then get me the output so I can replicate it.

PS Krita is redesigning the text feature, it isn't going to be on canvas just yet but the underlying code. On canvas will come after that. In the meantime, I am mostly waiting for 5.2 as new python apis I added should make things a bit easier

**Comment by cesar-pix** [comment]
Made some further testing, and the issue seems to be that there's other elements beside the text boxes in the vector layer, sorry if this was reported before, I'll just use one layer only for text in the meantime, but here's the output anyway:

```
==== Warning: Script not saved! ====
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<!-- Created using Krita: https://krita.org -->
<svg xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:krita="http://krita.org/namespaces/svg/krita"
    xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
    width="1440pt"
    height="810pt"
    viewBox="0 0 1440 810">
<defs/>
<rect id="shape0" transform="matrix(1.10650209169762 0 0 1.10650209169762 38.999999983795 37.125000016205)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><text id="t1_96_1412.2279792746114_WlxpWA" krita:useRichText="true" krita:textVersion="2" transform="translate(44.7668393782384, 310.310880829016)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-size="13.3333333333333"><tspan><tspan x="0" font-family="Montserrat" font-size="20" font-weight="700">Plano 00</tspan></tspan><tspan><tspan x="0" dy="26" font-family="Montserrat" font-size="20">Descripción</tspan></tspan></text><text id="t1_96_0130.96875_RbeO_w" krita:useRichText="true" krita:textVersion="2" transform="matrix(0.999999975310513 0 0 0.999999975310513 969.675454762216 316.712028751983)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-size="13.3333333333333"><tspan><tspan x="0" font-family="Montserrat" font-size="20" font-weight="700">Plano 00</tspan></tspan><tspan><tspan x="0" dy="25.5" font-family="Montserrat" font-size="20">Descripción</tspan></tspan></text><text id="t1_96_0130.96875_RbeO_w1" krita:useRichText="true" krita:textVersion="2" transform="matrix(0.999999975310513 0 0 0.999999975310513 508.820200550221 311.221483759321)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-size="13.3333333333333"><tspan><tspan x="0" font-family="Montserrat" font-size="20" font-weight="700">Plano 00</tspan></tspan><tspan><tspan x="0" dy="25.5" font-family="Montserrat" font-size="20">Descripción</tspan></tspan></text><rect id="shape01" transform="matrix(1.10650208959136 0 0 1.10650208959136 500.497134475048 38.2896064371058)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><rect id="shape011" transform="matrix(1.10650208959136 0 0 1.10650208959136 961.908501728173 43.2688657959524)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><rect id="shape02" transform="matrix(1.10650208959136 0 0 1.10650208959136 42.4052734611543 421.50591178407)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><rect id="shape03" transform="matrix(1.10650208959136 0 0 1.10650208959136 505.476393833895 419.846158664454)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><rect id="shape04" transform="matrix(1.10650208959136 0 0 1.10650208959136 965.228007967404 421.50591178407)" fill="none" stroke="#000000" stroke-width="1.4625" stroke-linecap="square" stroke-linejoin="bevel" width="388.5" height="218.25"/><text id="shape07" krita:useRichText="true" krita:textVersion="2" transform="matrix(0.999999975310513 0 0 0.999999975310513 49.4575910706358 696.7156645498)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-family="Montserrat" font-size="20" font-size-adjust="0.400298" font-stretch="normal" letter-spacing="0" word-spacing="0"><tspan x="0" font-weight="700">Plano 00</tspan><tspan x="0" dy="25.5">Descripción</tspan></text><text id="shape08" krita:useRichText="true" krita:textVersion="2" transform="matrix(0.999999975310513 0 0 0.999999975310513 510.228550156492 695.391610069668)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-family="Montserrat" font-size="20" font-size-adjust="0.400298" font-stretch="normal" letter-spacing="0" word-spacing="0"><tspan x="0" font-weight="700">Plano 00</tspan><tspan x="0" dy="25.5">Descripción</tspan></text><text id="shape09" krita:useRichText="true" krita:textVersion="2" transform="matrix(0.999999936374301 0 0 0.999999936374301 970.915198283266 696.521310099994)" fill="#000000" stroke-opacity="0" stroke="#000000" stroke-width="0" stroke-linecap="square" stroke-linejoin="bevel" font-family="Montserrat" font-size="20" font-size-adjust="0.400298" font-stretch="normal" letter-spacing="0" word-spacing="0"><tspan x="0" font-weight="700">Plano 00</tspan><tspan x="0" dy="25.5">Descripción</tspan></text>
</svg>
```

Hope it helps

**Comment by KnowZero** [comment]
Okay, try now

**Comment by cesar-pix** [comment]
Awesome! Thanks a lot for this tool, it was the only thing I was missing in Krita.
